/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as ProntaEntregaRouteImport } from './routes/pronta-entrega'
import { Route as VitrineRouteImport } from './routes/vitrine'
import { Route as CCodeRouteImport } from './routes/c.$code'
import { Route as ClienteClientIdRouteImport } from './routes/cliente.$clientId'
import { Route as ContaTokenRouteImport } from './routes/conta.$token'
import { Route as ReciboCompraPurchaseIdRouteImport } from './routes/recibo.compra.$purchaseId'
import { Route as ReciboPagamentoPaymentIdRouteImport } from './routes/recibo.pagamento.$paymentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProntaEntregaRoute = ProntaEntregaRouteImport.update({
  id: '/pronta-entrega',
  path: '/pronta-entrega',
  getParentRoute: () => rootRouteImport,
} as any)
const VitrineRoute = VitrineRouteImport.update({
  id: '/vitrine',
  path: '/vitrine',
  getParentRoute: () => rootRouteImport,
} as any)
const CCodeRoute = CCodeRouteImport.update({
  id: '/c/$code',
  path: '/c/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteClientIdRoute = ClienteClientIdRouteImport.update({
  id: '/cliente/$clientId',
  path: '/cliente/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaTokenRoute = ContaTokenRouteImport.update({
  id: '/conta/$token',
  path: '/conta/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ReciboCompraPurchaseIdRoute = ReciboCompraPurchaseIdRouteImport.update({
  id: '/recibo/compra/$purchaseId',
  path: '/recibo/compra/$purchaseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReciboPagamentoPaymentIdRoute =
  ReciboPagamentoPaymentIdRouteImport.update({
    id: '/recibo/pagamento/$paymentId',
    path: '/recibo/pagamento/$paymentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/loja': typeof LojaRoute
  '/produtos': typeof ProdutosRoute
  '/pronta-entrega': typeof ProntaEntregaRoute
  '/vitrine': typeof VitrineRoute
  '/c/$code': typeof CCodeRoute
  '/cliente/$clientId': typeof ClienteClientIdRoute
  '/conta/$token': typeof ContaTokenRoute
  '/recibo/compra/$purchaseId': typeof ReciboCompraPurchaseIdRoute
  '/recibo/pagamento/$paymentId': typeof ReciboPagamentoPaymentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/loja': typeof LojaRoute
  '/produtos': typeof ProdutosRoute
  '/pronta-entrega': typeof ProntaEntregaRoute
  '/vitrine': typeof VitrineRoute
  '/c/$code': typeof CCodeRoute
  '/cliente/$clientId': typeof ClienteClientIdRoute
  '/conta/$token': typeof ContaTokenRoute
  '/recibo/compra/$purchaseId': typeof ReciboCompraPurchaseIdRoute
  '/recibo/pagamento/$paymentId': typeof ReciboPagamentoPaymentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/loja': typeof LojaRoute
  '/produtos': typeof ProdutosRoute
  '/pronta-entrega': typeof ProntaEntregaRoute
  '/vitrine': typeof VitrineRoute
  '/c/$code': typeof CCodeRoute
  '/cliente/$clientId': typeof ClienteClientIdRoute
  '/conta/$token': typeof ContaTokenRoute
  '/recibo/compra/$purchaseId': typeof ReciboCompraPurchaseIdRoute
  '/recibo/pagamento/$paymentId': typeof ReciboPagamentoPaymentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes'
    | '/loja'
    | '/produtos'
    | '/pronta-entrega'
    | '/vitrine'
    | '/c/$code'
    | '/cliente/$clientId'
    | '/conta/$token'
    | '/recibo/compra/$purchaseId'
    | '/recibo/pagamento/$paymentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajustes'
    | '/loja'
    | '/produtos'
    | '/pronta-entrega'
    | '/vitrine'
    | '/c/$code'
    | '/cliente/$clientId'
    | '/conta/$token'
    | '/recibo/compra/$purchaseId'
    | '/recibo/pagamento/$paymentId'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/loja'
    | '/produtos'
    | '/pronta-entrega'
    | '/vitrine'
    | '/c/$code'
    | '/cliente/$clientId'
    | '/conta/$token'
    | '/recibo/compra/$purchaseId'
    | '/recibo/pagamento/$paymentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  LojaRoute: typeof LojaRoute
  ProdutosRoute: typeof ProdutosRoute
  ProntaEntregaRoute: typeof ProntaEntregaRoute
  VitrineRoute: typeof VitrineRoute
  CCodeRoute: typeof CCodeRoute
  ClienteClientIdRoute: typeof ClienteClientIdRoute
  ContaTokenRoute: typeof ContaTokenRoute
  ReciboCompraPurchaseIdRoute: typeof ReciboCompraPurchaseIdRoute
  ReciboPagamentoPaymentIdRoute: typeof ReciboPagamentoPaymentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pronta-entrega': {
      id: '/pronta-entrega'
      path: '/pronta-entrega'
      fullPath: '/pronta-entrega'
      preLoaderRoute: typeof ProntaEntregaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vitrine': {
      id: '/vitrine'
      path: '/vitrine'
      fullPath: '/vitrine'
      preLoaderRoute: typeof VitrineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$code': {
      id: '/c/$code'
      path: '/c/$code'
      fullPath: '/c/$code'
      preLoaderRoute: typeof CCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/$clientId': {
      id: '/cliente/$clientId'
      path: '/cliente/$clientId'
      fullPath: '/cliente/$clientId'
      preLoaderRoute: typeof ClienteClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/$token': {
      id: '/conta/$token'
      path: '/conta/$token'
      fullPath: '/conta/$token'
      preLoaderRoute: typeof ContaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recibo/compra/$purchaseId': {
      id: '/recibo/compra/$purchaseId'
      path: '/recibo/compra/$purchaseId'
      fullPath: '/recibo/compra/$purchaseId'
      preLoaderRoute: typeof ReciboCompraPurchaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recibo/pagamento/$paymentId': {
      id: '/recibo/pagamento/$paymentId'
      path: '/recibo/pagamento/$paymentId'
      fullPath: '/recibo/pagamento/$paymentId'
      preLoaderRoute: typeof ReciboPagamentoPaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  LojaRoute: LojaRoute,
  ProdutosRoute: ProdutosRoute,
  ProntaEntregaRoute: ProntaEntregaRoute,
  VitrineRoute: VitrineRoute,
  CCodeRoute: CCodeRoute,
  ClienteClientIdRoute: ClienteClientIdRoute,
  ContaTokenRoute: ContaTokenRoute,
  ReciboCompraPurchaseIdRoute: ReciboCompraPurchaseIdRoute,
  ReciboPagamentoPaymentIdRoute: ReciboPagamentoPaymentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
